// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxibdwzpvjbxtkhqecgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4aWJkd3pwdmpieHRraHFlY2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjYzODAsImV4cCI6MjA1OTUwMjM4MH0.QZPr0dLUVoOEJ9n_MDFwVh2mDnR96QwlHtiVJfcNpEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);